Draft: Message meta
appform-io/memq pull request #11
Opened 2024-05-03 05:15 UTC by tusharmndr

2024-05-03 05:59 UTC, santanusinha requested changes

2024-05-03 05:59 UTC, santanusinha commented on memq-actor/src/main/java/io/appform/memq/ActorSystem.java
> +import java.util.function.*;
revert

2024-05-03 05:59 UTC, santanusinha commented on memq-actor/src/main/java/io/appform/memq/actor/InternalMessage.java
> +//package private class
what is this?

2024-05-03 05:59 UTC, santanusinha commented on memq-actor/src/main/java/io/appform/memq/actor/MessageMeta.java
> +    private int deliveryAttempt;
make this volatile/atomic for safety

2024-05-03 08:08 UTC, tusharmndr commented on memq-actor/src/main/java/io/appform/memq/ActorSystem.java
> +import java.util.function.*;
Done

2024-05-03 08:08 UTC, tusharmndr commented on memq-actor/src/main/java/io/appform/memq/actor/InternalMessage.java
> +//package private class
Removed

2024-05-03 08:09 UTC, tusharmndr commented on memq-actor/src/main/java/io/appform/memq/actor/MessageMeta.java
> +    private int deliveryAttempt;
Done

2024-05-24 05:04 UTC, santanusinha approved these changes

2024-05-24 05:04 UTC, merged